name: dslink_system
description: System DSLink
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  path: any
  intl: any
  collection: "1.12.0" # Fixes a bug with an uncompilable dependency.
